export const SET_LOADER = "SET_LOADER";
export const API_ERROR = "API_ERROR";
export const GETOTP = 'GET_OTP';
export const VERIFYOTP = 'VERIFY_OTP';
export const ALL_CATEGORIES = 'ALL_CATEGORIES';
export const VIEW_CART_BY_ID = 'VIEW_CART_BY_ID';
export const REMOVE_ITEM_TO_CART = 'REMOVE-ITEM-TO-CART';
export const MEDICINE_CATEGORY_VIEW_ALL = 'MEDICINE CATEGORY_VIEW_ALL';
export const GET_ALTERNATEMEDICINE = 'GET_ALTERNATEMEDICINE';
export const STORE_LOCATION_VIEW_ALL = 'STORE_LOCATION_VIEW_ALL';
export const VIEW_BY_CATEGORIES = 'VIEW_BY_CATEGORIES';
export const VIEW_ALL_MEDICINE = 'VIEW_ALL_MEDICINE';
export const VIEW_BY_MEDICINE_ID = 'VIEW_BY_MEDICINE_ID';
export const CALLREQUEST = 'CALLREQUEST';
export const USER_PRESCRIPTION_UPLOAD = 'USER_PRESCRIPTION_UPLOAD';
export const PINCODE = 'PINCODE';
export const USER_ADDRESS_DELETE = 'USER_ADDRESS_DELETE';
export const USER_VIEW_BY_ID = 'USER_VIEW_BY_ID';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const CLICKHERE_OFFER = 'CLICKHERE_OFFER';
export const CONTACT_US = 'CONTACT_US';



